# OpenAPI Specification TEMPLATE for a Dynamic Tariff Price API.
# Based on the VSE standard https://www.strom.ch/de/shop/dynamische-netznutzungstarife-im-verteilnetz-hdn-ch-2025.
# This template contains the essential endpoints and schemas.
#
# Provided by SmartGridready: https://smartgridready.ch/loesungen/dynamischetarife
# Author: Matthias Krebs
#
# Version 1.0.5 (2026-05-28)
#

openapi: 3.0.3
info:
  title: Dynamic Tariff Retrieval API
  description: |
    API to retrieve dynamic tariff prices of an electricity provider.
    Follows the VSE standard https://www.strom.ch/de/shop/dynamische-netznutzungstarife-im-verteilnetz-hdn-ch-2025.
  version: '1.0.5'
servers:
  # TODO: Replace this with your actual API URL - endpoint paths will be relative to this URL
  - url: https://tariffs.example.org/api/v1
    description: Example server
paths:
  /tariffs:
    get:
      summary: Retrieve dynamic tariff prices
      description: This endpoint retrieves dynamic tariff prices in a given time period.
      operationId: get-tariffs
      parameters:
        - name: tariff_type
          in: query
          description: Filters by tariff type. If omitted, all available tariff types are returned.
          schema:
            $ref: '#/components/schemas/TariffType'
        - name: tariff_name
          in: query
          description: Filters by a specific tariff product of the provider. If omitted, the provider's default tariff is returned.
          schema:
            $ref: '#/components/schemas/TariffName'
        - name: start_timestamp
          in: query
          description: |
            Marks the begin of the price retrieval period. If omitted, the begin of the current day is utilized.
            The `start_timestamp` of the first returned interval should match this parameter.
          schema:
            $ref: '#/components/schemas/TimeStamp'
          example: '2026-01-01T00:00:00+01:00'
        - name: end_timestamp
          in: query
          description: |
            Marks the end of the price retrieval period. If omitted, the begin of the following day is utilized.
            The `end_timestamp` of the last returned interval should match this parameter.
          schema:
            $ref: '#/components/schemas/TimeStamp'
          example: '2026-01-02T00:00:00+01:00'
      responses:
        '200':
          description: Dynamic tariff prices retrieved successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TariffResponse'
              example:
                publication_timestamp: '2026-01-31T18:00:00+01:00'
                prices:
                  - start_timestamp: '2026-02-01T00:00:00+01:00'
                    end_timestamp: '2026-02-01T00:15:00+01:00'
                    electricity:
                      - unit: CHF_kWh
                        value: 0.121
                    grid:
                      - unit: CHF_kWh
                        value: 0.113
                      - unit: CHF_m
                        value: 5
                    integrated:
                      - unit: CHF_kWh
                        value: 0.234
                      - unit: CHF_m
                        value: 5
                  - start_timestamp: '2026-02-01T00:15:00+01:00'
                    end_timestamp: '2026-02-01T00:30:00+01:00'
                    electricity:
                      - unit: CHF_kWh
                        value: 0.123
                    grid:
                      - unit: CHF_kWh
                        value: 0.102
                      - unit: CHF_m
                        value: 5
                    integrated:
                      - unit: CHF_kWh
                        value: 0.225
                      - unit: CHF_m
                        value: 5
        '400':
          description: Incorrect query parameters were given.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: "Invalid tariff_name 'xyz'. Allowed values: 'example_tariff'."
        '500':
          description: An internal server error occurred.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: An internal error occurred.
components:
  schemas:
    PriceArray:
      type: array
      items:
        $ref: '#/components/schemas/Price'
      description: Contains the prices for the requested time intervals.
    Price:
      type: object
      required:
        - start_timestamp
        - end_timestamp
      properties:
        start_timestamp:
          $ref: '#/components/schemas/TimeStamp'
        end_timestamp:
          $ref: '#/components/schemas/TimeStamp'
      anyOf:
        - properties:
            electricity:
              $ref: '#/components/schemas/PriceComponentArray'
        - properties:
            grid:
              $ref: '#/components/schemas/PriceComponentArray'
        - properties:
            integrated:
              $ref: '#/components/schemas/PriceComponentArray'
        - properties:
            regional_fees:
              $ref: '#/components/schemas/PriceComponentArray'
        - properties:
            feed_in:
              $ref: '#/components/schemas/PriceComponentArray'
      description: A price item of a time interval, contains tariff components.
    PriceComponentArray:
      type: array
      items:
        $ref: '#/components/schemas/PriceComponent'
      description: Price components of a tariff component.
    PriceComponent:
      type: object
      required:
        - unit
        - value
      properties:
        unit:
          $ref: '#/components/schemas/PriceUnit'
        value:
          $ref: '#/components/schemas/PriceValue'
      additionalProperties: true
    TariffName:
      type: string
      enum:
      # TODO: Define your actual tariff product names here, since they are provider-specific
        - example_tariff
      description: |
        Tariff names specified by DSO
          * `example_tariff` - An example tariff
    TariffType:
      type: string
      enum:
        - electricity
        - grid
        - integrated
        - regional_fees
        - feed_in
      description: |
        Tariff types (components) specified by VSE
          * `electricity` - Electricity energy supply to end consumers
          * `grid` - Grid usage (distribution and transmission networks) including general and individual system services, grid surcharge according to Art. 35 EnG + electricity reserve + socialized costs via the transmission grid
          * `integrated` - Combination of `electricity` and `grid`
          * `regional_fees` - Local or regional surcharges (e.g., concession fees)
          * `feed_in` - Compensation for feed-in into grid (positive value means reimbursement of customer)
    PriceUnit:
      type: string
      enum:
        - CHF_kWh
        - CHF_kVarh
        - CHF_y
        - CHF_m
        - CHF_w
        - CHF_d
        - CHF_12h
        - CHF_6h
        - CHF_4h
        - CHF_2h
        - CHF_1h
        - CHF_30min
        - CHF_15min
        - CHF_kW_y
        - CHF_kW_m
        - CHF_kW_w
        - CHF_kW_d
        - CHF_kW_12h
        - CHF_kW_6h
        - CHF_kW_4h
        - CHF_kW_2h
        - CHF_kW_1h
        - CHF_kW_30min
        - CHF_kW_15min
      description: |
        Price unit:
          * `CHF_kWh` - CHF per kWh
          * `CHF_kVarh` - CHF per kVarh
          * `CHF_y` - CHF per year
          * `CHF_m` - CHF per month
          * `CHF_w` - CHF per week
          * `CHF_d` - CHF per day
          * `CHF_12h` - CHF per 12 hours
          * `CHF_6h` - CHF per 6 hours
          * `CHF_4h` - CHF per 4 hours
          * `CHF_2h` - CHF per 2 hours
          * `CHF_1h` - CHF per hour
          * `CHF_30min` - CHF per 30 minutes
          * `CHF_15min` - CHF per 15 minutes
          * `CHF_kW_y` - CHF per kW per year
          * `CHF_kW_m` - CHF per kW per month
          * `CHF_kW_w` - CHF per kW per week
          * `CHF_kW_d` - CHF per kW per day
          * `CHF_kW_12h` - CHF per kW per 12 hours
          * `CHF_kW_6h` - CHF per kW per 6 hours
          * `CHF_kW_4h` - CHF per kW per 4 hours
          * `CHF_kW_2h` - CHF per kW per 2 hours
          * `CHF_kW_1h` - CHF per kW per hour
          * `CHF_kW_30min` - CHF per kW per 30 minutes
          * `CHF_kW_15min` - CHF per kW per 15 minutes
    PriceValue:
      type: number
      format: decimal
      description: A numeric price value.
    TimeStamp:
      type: string
      anyOf:
        - format: date-time
        - format: empty
      description: An ISO-8601 time stamp with time zone offset.
      example: '2026-05-23T13:30:00+02:00'
    TariffResponse:
      type: object
      required:
        - publication_timestamp
        - prices
      properties:
        publication_timestamp:
          $ref: '#/components/schemas/TimeStamp'
        prices:
          $ref: '#/components/schemas/PriceArray'
      additionalProperties: true
    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: The error message.
